# Generated by Django 5.1.1 on 2024-09-20 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantMenus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='mealCategories',
            new_name='meal_categories',
        ),
    ]
